<a href="https://colab.research.google.com/github/Nitin-Dwivedi-7/HSI-/blob/master/HSI_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
import numpy as np                                       #importing all the libs
import scipy as s
from scipy.io import loadmat
import matplotlib.pyplot as plt
from keras.callbacks import ModelCheckpoint, TensorBoard


import pylab as plt
import pandas as pd
import tensorflow as  tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten, Dropout, LSTM
import tensorflow.keras.layers as kl
from tensorflow.keras.layers import BatchNormalization 
from tensorflow.keras import regularizers

Using TensorFlow backend.


In [0]:
data1= loadmat("/content/drive/My Drive/data sets/Salinas_corrected.mat")          #import
image=data1["salinas_corrected"] 

data2=loadmat("/content/drive/My Drive/data sets/Salinas_gt.mat")                                #import
ground_truth=data2["salinas_gt"]               #storing array from dict to a var



In [18]:
image_with_gt = np.dstack((image, ground_truth))
final_output = image_with_gt.reshape(ground_truth.size, image.shape[2]+1)
data=pd.DataFrame(final_output)
data.shape

(111104, 205)

In [19]:
data = data[data.iloc[:, -1] != 0]
data.shape

(54129, 205)

In [0]:
gt=data.loc[:,data.shape[1]-1]
dataset=data.loc[:, 0:data.shape[1]-2]

In [21]:
from sklearn import preprocessing
dataset = preprocessing.scale(dataset)
pd.DataFrame(dataset).head()

0         1         2    ...       201       202       203
0  0.139160  1.146405  1.193081  ...  0.048395 -0.601151 -0.186720
1  1.249739  0.139285  1.193081  ...  0.139396  0.066622  0.645191
2  1.249739  1.146405  1.193081  ... -0.133606  0.066622 -0.035463
3  1.249739  1.146405  1.193081  ...  0.139396 -0.378560 -0.337977
4  1.249739  0.139285  1.193081  ... -0.133606 -0.155969 -0.035463

[5 rows x 204 columns]

In [22]:
from sklearn.decomposition import PCA 
pca = PCA(n_components = 100) 
dataset_p = pca.fit_transform(dataset) 
 
print(dataset_p.shape) 
pd.DataFrame(dataset_p).head()

(54129, 100)


0          1         2   ...        97        98        99
0  7.370062  14.608778 -4.599675  ...  0.028950  0.006347 -0.033009
1  7.363425  13.659417 -4.158736  ...  0.002444 -0.002899 -0.003123
2  7.378918  13.431269 -4.128623  ... -0.002005 -0.026463 -0.013925
3  7.388459  15.706656 -4.729384  ...  0.029382 -0.003052 -0.036639
4  7.586524  16.732894 -4.923359  ...  0.004892 -0.007464  0.028717

[5 rows x 100 columns]

In [81]:
from sklearn.preprocessing import OneHotEncoder 

onehotencoder = OneHotEncoder() 
gt = onehotencoder.fit_transform(np.array(gt).reshape(-1,1)).toarray() 
print(gt)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [82]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(dataset_p,gt, test_size=0.30, random_state=42)
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)


(37890, 100) (37890, 16) (16239, 100) (16239, 16)


In [87]:
first_layer_size = 32                  #############################nodes in first layer
model = Sequential()
model.add(Dense(first_layer_size, activation='sigmoid', input_shape=(100,)))#####################adding layers
model.add(Dense(100, activation='sigmoid'))
model.add(Dense(100, activation='sigmoid'))
model.add(Dense(16, activation='softmax' ))

model.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_37 (Dense)             (None, 32)                3232      
_________________________________________________________________
dense_38 (Dense)             (None, 100)               3300      
_________________________________________________________________
dense_39 (Dense)             (None, 100)               10100     
_________________________________________________________________
dense_40 (Dense)             (None, 16)                1616      
Total params: 18,248
Trainable params: 18,248
Non-trainable params: 0
_________________________________________________________________


In [0]:
from keras.models import Sequential,model_from_json
from keras.layers import Dense
from keras.optimizers import RMSprop
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])


In [89]:
print(train_X.shape)
print(train_y.shape)
print(test_X.shape)
print(test_y.shape)

(37890, 100)
(37890, 16)
(16239, 100)
(16239, 16)


In [91]:

history = model.fit(train_X,train_y,
                    batch_size=1000,
                    epochs=500,
                    verbose=1)


Epoch 1/500
37890/37890 [==============================] - 0s 6us/step - loss: 0.1322 - accuracy: 0.9474
Epoch 2/500
37890/37890 [==============================] - 0s 6us/step - loss: 0.1317 - accuracy: 0.9478
Epoch 3/500
37890/37890 [==============================] - 0s 6us/step - loss: 0.1304 - accuracy: 0.9483
Epoch 4/500
37890/37890 [==============================] - 0s 6us/step - loss: 0.1304 - accuracy: 0.9478
Epoch 5/500
37890/37890 [==============================] - 0s 6us/step - loss: 0.1292 - accuracy: 0.9489
Epoch 6/500
37890/37890 [==============================] - 0s 6us/step - loss: 0.1296 - accuracy: 0.9479
Epoch 7/500
37890/37890 [==============================] - 0s 6us/step - loss: 0.1277 - accuracy: 0.9494
Epoch 8/500
37890/37890 [==============================] - 0s 6us/step - loss: 0.1266 - accuracy: 0.9495
Epoch 9/500
37890/37890 [==============================] - 0s 6us/step - loss: 0.1260 - accuracy: 0.9497
Epoch 10/500
37890/37890 [=============================

In [95]:
score = model.evaluate(test_X, test_y, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])


Test loss: 0.109007554094739
Test accuracy: 0.962189793586731


In [101]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
prediction = model.predict(test_X)
pd.DataFrame(prediction)

0             1   ...            14            15
0      1.244482e-12  1.000000e+00  ...  1.026120e-27  8.288517e-13
1      1.938571e-26  1.126437e-24  ...  6.003495e-10  2.976902e-19
2      2.161118e-28  9.803005e-18  ...  7.735239e-15  2.697827e-20
3      1.000000e+00  1.035972e-10  ...  3.186347e-21  2.330023e-08
4      3.555527e-15  1.616428e-23  ...  9.984506e-01  2.316081e-11
...             ...           ...  ...           ...           ...
16234  5.396915e-11  4.435988e-22  ...  1.308552e-02  4.537613e-09
16235  5.486642e-11  2.007704e-21  ...  6.806104e-02  4.829841e-08
16236  7.184018e-12  6.303631e-22  ...  9.091882e-01  1.781244e-09
16237  9.236895e-11  5.281238e-21  ...  1.190383e-01  1.113089e-08
16238  1.105903e-25  1.461842e-15  ...  2.500246e-14  3.969722e-18

[16239 rows x 16 columns]